theme: jekyll-theme-cayman
title: [Raft - Overview, implementation and performance analysis]
description: [Interactive paper that explored Raft consensus protocol]
show_downloads: ["true"]

github:
  zip_url: https://github.com/araragao/raft/raw/main/implementation.zip
  paper_url: https://github.com/araragao/raft/blob/main/paper/raft-paper.pdf
